### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by amilino** [jez500/chorus2#110] opened 2016-04-18 16:09 UTC
Unable to install chorus2, previously I had installed chorus first version and everyging worked fine. After uninstalling first release I was unable to install second. My envuronment is Kodi 16.0 on Raspbian Jessie.

Please help.

Regards,
Alan

**Comment by amilino** [comment] 2016-04-19 16:59
Any help on this one, please. I realy like this web interface and would like to see second version...

**Comment by driet** [comment] 2016-04-19 18:12
Running OSMC on Raspi 2. Just extracted the webinterface.kodi.2.0.14.zip an put the content through sftp into kodi/addons/webinterface.kodi/. Do not use the old chorus folder! Then did the settings like here https://github.com/jez500/chorus2/blob/master/readme.md.
Another way may be http://kodi.wiki/view/Add-on_manager#How_to_install_from_a_ZIP_file

**Comment by amilino** [comment] 2016-04-20 06:38
Doesn't work. I extracted files and tried with "http://.../addons/webinterface.kodi/". Also installation from zip doesn't work.

**Comment by amilino** [comment] 2016-04-20 06:45
Oh, it's working finally. I extracted this folder: chorus2-master.zip\chorus2-master\dist\

**Comment by pcbona** [comment] 2016-08-13 12:06
I ran into the same problem. Tried to Install the downloaded chorus2.master.zip file. You have to unzip this and install the following file within: \chorus2-master\chorus2-master\webinterface.kodi.2.0.14.zip

Just in case anyone else is having this issue.

**Comment by jez500** [comment] 2016-10-10 04:56
Duplicate of #113

**Closed by jez500** 2016-10-10 04:56 UTC
